version: '3'

services:

  web:
    container_name: blog-web
    image: nginx:1.21.3-alpine
    ports:
      - '80:80'
    volumes:
      - ./nginx/conf:/etc/nginx/conf.d
      - ./nginx/uwsgi_params:/etc/nginx/uwsgi_params
      - ./src/static:/static
    depends_on:
      - app

  app:
    container_name: blog-app
    build: ./django
    command: uwsgi --socket :8001 --module config.wsgi --py-autoreload 1 --logto /tmp/tmp.log
    volumes:
      - ./src:/workspace
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=P@ssw0rd
      - POSTGRES_HOST=blog-db
      - POSTGRES_PORT=5432
    expose:
      - '8001'
    depends_on:
      - db

  db:
    image: postgres:latest
    container_name: blog-db
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=P@ssw0rd
    ports:
      - 5432:5432
    volumes:
      - ./db/postgres:/var/lib/postgresql/data
      - ./db/logs:/var/log
