# Generated by Django 3.2.7 on 2022-08-26 10:27

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='タグ')),
            ],
            options={
                'verbose_name': 'タグ',
                'verbose_name_plural': 'タグ',
            },
        ),
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='無題', max_length=200, verbose_name='タイトル')),
                ('text', models.TextField(blank=True, null=True, verbose_name='本文')),
                ('post_dt', models.DateTimeField(default=django.utils.timezone.now, verbose_name='作成日時')),
                ('publication_start_date', models.DateTimeField(blank=True, null=True, verbose_name='公開開始日時')),
                ('publication_end_date', models.DateTimeField(blank=True, null=True, verbose_name='公開終了日時')),
                ('is_private', models.BooleanField(default=True, verbose_name='非公開')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='削除')),
                ('tag', models.ManyToManyField(to='blog.Tag')),
            ],
            options={
                'verbose_name': '記事',
                'verbose_name_plural': '記事',
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='NO NAME', max_length=200, verbose_name='名前')),
                ('text', models.TextField(blank=True, null=True, verbose_name='本文')),
                ('post_dt', models.DateTimeField(default=django.utils.timezone.now, verbose_name='投稿日時')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='削除')),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment', to='blog.entry', verbose_name='記事')),
            ],
            options={
                'verbose_name': 'コメント',
                'verbose_name_plural': 'コメント',
            },
        ),
    ]
