# Generated by Django 3.2.7 on 2022-08-26 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='tag',
            field=models.ManyToManyField(blank=True, null=True, related_name='entry', to='blog.Tag', verbose_name='タグ'),
        ),
    ]
